# Generated by Django 4.0.1 on 2022-01-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='winning_timestamps',
            field=models.JSONField(blank=True, help_text="Today's winning timestamps", null=True, verbose_name='Winning timestamps'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='perday',
            field=models.IntegerField(help_text="Prize's maximum wins in a single day", verbose_name='Per day'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='won_today',
            field=models.IntegerField(blank=True, default=0, help_text='Number of times the prize has been won today', verbose_name='Won today'),
        ),
    ]
