# Generated by Django 4.0.2 on 2022-02-04 23:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='allowed_users',
            field=models.ManyToManyField(help_text='Users allowed to partecipate to this contest', related_name='allowed_contests', to=settings.AUTH_USER_MODEL, verbose_name='Allowed users'),
        ),
        migrations.AlterField(
            model_name='utente',
            name='WMAX',
            field=models.IntegerField(blank=True, default=1, help_text='Number of times the prize can be won by this user today', verbose_name='Max wins perday'),
        ),
    ]
