# Generated by Django 4.0.2 on 2022-02-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_alter_contest_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='won_contests',
            field=models.JSONField(blank=True, help_text="Today's winning timestamps", null=True, verbose_name=''),
        ),
    ]
